name: stop-watch-app-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        
      - name: Run Integration Test
        run: cat newfile
